# Dependencies
#markdown:         redcarpet
highlighter:      rouge

# Permalinks
#permalink:        pretty
#relative_permalinks: true

# Setup
title:            Purnata Ghosal
tagline:          'PhD'
description:      'Postdoc (CS Theory), Liverpool'
url:              https://purnatag.github.io
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo
future:		  TRUE
timezone:		  TIMEZONE

#paginate:         5

# Custom vars
#version:          2.1.0

#github:
#  repo:           https://github.com/poole/hyde
